import type { ThemeSpec } from '../types.ts'

/** Arctic blue-grey, after the Nord palette (nord0–nord15). */
export const nord: ThemeSpec = {
  id: 'nord',
  label: 'Nord',
  blurb: 'Arctic, north-bluish. Cool greys with a frost accent.',
  variants: {
    dark: {
      bg: '#2e3440',
      surface: '#3b4252',
      overlay: '#434c5e',
      sidebar: '#2b303b',
      fg: '#eceff4',
      muted: '#d8dee9',
      faint: '#9099ab',
      border: '#4c566a',
      accent: '#88c0d0',
      info: '#81a1c1',
      error: '#bf616a',
      success: '#a3be8c',
      warn: '#ebcb8b',
      code: {
        bg: '#2b303b',
        comment: '#7b88a1',
        keyword: '#81a1c1',
        string: '#a3be8c',
        constant: '#b48ead',
        function: '#88c0d0',
        parameter: '#d8dee9',
        punctuation: '#d8dee9',
        link: '#8fbcbb',
      },
    },
    light: {
      bg: '#eceff4',
      surface: '#ffffff',
      overlay: '#ffffff',
      sidebar: '#e5e9f0',
      fg: '#2e3440',
      muted: '#3b4252',
      faint: '#66718a',
      border: '#d8dee9',
      accent: '#5e81ac',
      info: '#5e81ac',
      error: '#a54a53',
      success: '#4f7a3f',
      warn: '#a3792f',
      code: {
        bg: '#e5e9f0',
        comment: '#69758c',
        keyword: '#5e81ac',
        string: '#4f7a3f',
        constant: '#8a5b86',
        function: '#3b7d8c',
        parameter: '#3b4252',
        punctuation: '#434c5e',
        link: '#5e81ac',
      },
    },
  },
}
